[package]
name = "ato-cli"
version = "1.0.3"
edition = "2021"

[dependencies]
ato = { path = "../ato" }
clap = { version= "4.5.1", features=["derive"] }
tokio = { version = "1.36.0", features = ["full"] }

[[bin]]
name = "ato-cli"
path = "src/cli.rs"
