[package]
name = "ato-cli"
version = "0.1.4"
edition = "2021"

[dependencies]
ato = { path = "../ato" }
clap = { version= "4.5.1", features=["derive"] }


[[bin]]
name = "ato-cli"
path = "src/cli.rs"
