[package]
name = "ato"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
# rayon = "1.9.0"
walkdir="2.5.0"
md-5 = "0.10.6"

[lib]
name = "libato"
path = "src/lib.rs"

